language: rust

env:
  global:
  - RUST_BACKTRACE=full
  - KCOV_DIR=${HOME}/.cache/tools/kcov
  - CODECOV_DIR=${HOME}/.cache/tools/codecov

matrix:
  include:
  - os: linux
    dist: xenial
    env: MAKE_TARGET=coverage
    rust: nightly  # Running on nightly to ensure that all the traits are actually tested
  - os: linux
    dist: xenial
    rust: stable
    env: MAKE_TARGET=test-all-flavours
  - os: linux
    dist: xenial
    rust: nightly
    env: MAKE_TARGET=test-all-flavours
  - os: osx
    rust: stable
    env: MAKE_TARGET=test-all-flavours
  - os: osx
    rust: nightly
    env: MAKE_TARGET=test-all-flavours
  - os: windows
    rust: stable
    env: MAKE_TARGET=test-all-flavours
#  - os: windows  # TODO: run tests on nighly to ensure that pyo3 feature works on windows as well
#    rust: nightly
#    env: MAKE_TARGET=test-all-flavours PYTHON_SYS_EXECUTABLE=/C/Python37/python.exe
  - os: linux
    dist: xenial
    env: MAKE_TARGET=doc
    rust: stable
  - os: linux
    dist: xenial
    rust: nightly-2019-07-19  # Running on nighly to ensure that all the codebase are checked by the linters)
                              # Using an "older" nightly version due to difficulties into building rustfmt on latest nighyly
    env: MAKE_TARGET=lint
  allow_failures:
  - env: MAKE_TARGET=lint
  - os: osx
  - os: windows

install:
- bash scripts/travis/install.sh

before_script:
- bash scripts/travis/before_script.sh

script:
- make "${MAKE_TARGET}"

cache:
  timeout: 3600
  directories:
  - ${HOME}/.cache/pre-commit
  - ${CODECOV_DIR}
  - ${HOME}/.cargo/
  - ${TRAVIS_BUILD_DIR}/target
  - /C/ProgramData/chocolatey

# notifications:
#   email: false
#   slack:
#     # Personal Slack notification
#     secure: Something not set yet

deploy:
  provider: cargo
  token:
    secure: koNCxK/O/zVgWr6MKW7pFwkV5dhza4MySHwm+sEB5o67zcuLUfzQifpbQmHaJVskxq+KCriOImSLjxrZJDSPHAWnxktf1yWdP7/gGnQgbfI0jIYOSlCVsp8UClg+YDANrQcJjv1X34YevlU/kll0VnsQ3Ym9vuKWLQgrmoZQWx9bZs7znHS0Cd6ijTitD7E2gsPAYlRB0T8Y7pYU5MQd08wtP/1XPhIJyZ2RG6W+WPCv6js60Cqnxhx2cCBMRi8RKtS8lNEm21akVOPxmgeuQr4TY0lDNZlXFfz7ujjBSzUa2EYGQ2Ut8ds2UmeQ+M8cRRCpdgECI/PT6O/hQiez5wek61HX/Vz/qBISlzjw9Xg50Ts99Ga9PMcZLwPi8WTJFYyMSIZX00DluJ3qnQzTcCofBoFUWtwAuRukc98YNC2WBfty5F6xOg/1xhOL4i57YXR1Bz0dKFVgAJ6xrhT7t/KnSTApY47SzZhQgLGLdCk6gyOtaeeUA54z8S3jAEEstULWKOx4fHz+nU8kRtNQSin67RfHsLgxWj0cRnBiQ08fbdW/6BB6sEMvBOQ/HsEVkDpAMaZY/xBR9tF2CnAAqni7iQ6yuRO5nIPm5O3ytF/bMkDPPV5Wx+vnGSxfe74c2vA5V/HJGdvQHEiflUQ61G6mQr+0V2GrnYunHExSjiQ=
  on:
    condition: ${TRAVIS_REPO_SLUG} = macisamuele/json-trait-rs && ${MAKE_TARGET} = test && $(bash scripts/cargo-version.sh) = ${TRAVIS_TAG}
    tags: true
